### ISSUE TITLE
self.dev.set_configuration() Git is the latest version

### ISSUE THREAD

**Issue by WanManito** [pyusb/pyusb#325]
In 1.0.2, I run 'usb.util. Dispose_Resources (self.dev)' to release the resource,Then connect again without any problems
In the latest version of Git,Reconnection after the above operation will die at "self.dev.set_Configuration ()",
After testing, it should be me that releases the resource, and the child thread is still waiting "self.dev.read(self.inpoint, 64)",
An additional error exception is then fired,Then connect again at set Configuration and it gets stuck,Because in 1.0.2, this works fine,Just switching to the latest version creates this problem

**Comment by jonasmalacofilho** [comment]
> and the child thread is still waiting "self.dev.read(self.inpoint, 64)",

Calling `dispose_resources` on one thread while another tries to read from the device will lead to unexpected or undefined results.  We make no assurances that `Device` instances can be shared between threads.

> An additional error exception is then fired,

Can you provide both exceptions?

Additionally, were you already ignoring an exception to make 1.0.2 "work"?

---

Please see if you can `git bisect` the problem to a specific commit that introduces this change in behavior.

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/93034899-2709a380-f66e-11ea-8649-d62980bdc8a9.png)
Hello, this is my application mode. I run the "close function" and can't connect again

**Comment by jonasmalacofilho** [comment]
> An **additional** error exception is then fired,

Can you provide both exceptions?

And were you already ignoring an exception to make 1.0.2 "work"?

---

Please also see if you can `git bisect` the problem to a specific commit that introduces this change in behavior.

**Comment by WanManito** [comment]
Hello, I guess the above problem in version 1.1 is due to multithreading programming. The figure above is the way I implemented it. I don't know why. The following figure is the additional exception
![image](https://user-images.githubusercontent.com/26118508/93409188-e0fc4c00-f8c8-11ea-8680-2e96d7ea8337.png)

**Comment by WanManito** [comment]
Could you give me some Pointers

**Comment by WanManito** [comment]
Could you give me some Pointers @jonasmalacofilho

**Comment by jonasmalacofilho** [comment]
Ideally I would have the reader thread "own" the device handle, and add an abstraction to allow other threads to ask the reader to: (a) stop trying to read; and (b) unclaim the interface and otherwise release the device.

The specifics on how to implement this will vary a bit depending on what else your software has to do; I also don't know of the top of my head the best way to implement this using libusb synchronous APIs (which are the only ones PyUSB supports right now).

---

Another approach is to simply get a new handle after the problem happens (so that you don't get stuck in `set_configuration`).

Again, I think you really need should solve your concurrency (because it is _not_ sound to access the handle from multiple threads), but maybe keeping this other approach in mind may help if you need a hack to overcome our limitation of only supporting the synchronous APIs.

**Comment by WanManito** [comment]
@jonasmalacofilho Thank you for your reply. I get the dev object in the child thread and release the resource when the thread stops
