### ISSUE TITLE
Thonny Issues

### ISSUE THREAD

**Issue by Desperate4HelpIntern** [pyusb/pyusb#382]
Hi, I'm an intern and I am using a python program called Thonny to communicate with a raspberry pi.  I followed the instructions to install pyusb through pip (Command Prompt Input: pip install pyusb) and I followed the tutorial instructions for importing pyusb: (Thonny: import usb.core import usb.util) however, Thonny claims that there is no module named usb.  I set up a virtual python enviornment and I have it running through Thonny, so there should be no language conflicts (using micropython instead of python).  What can I do to fix this issue?

**Comment by jonasmalacofilho** [comment]
[Apparently,](https://github.com/thonny/thonny/wiki/InstallingPackages) when using Thonny, you need to install packages through their interface.  Additionally, not all packages may be available, since you're (by default) limited to their curated distribution.

Honestly, it's possible that you have already outgrown Thonny (you're already using virtual environments).
