### ISSUE TITLE
SCSI command or ioctl pass-through vendor command

### ISSUE THREAD

**Issue by gsegria** [pyusb/pyusb#392]
Hi all,

Does pyusb support usb ioctl vendor command?

**Comment by jonasmalacofilho** [comment]
@mcuee, I'm not familiar with these areas... can you take this one?

---

If I had to guess, and because PyUSB wraps libusb, it should generally be possible to create pretty much any USB request that is wanted, including any SCSI commands at the USB level.

On the other hand, since a generic driver is used to access the device (e.g.`usbfs`) instead of the appropriate class specific driver (e.g. for USB Mass Storage), I don't think ioctls would be available.  Plus we don't yet expose the associated file descriptor (and I don't know if libusb even supports that on all platforms).

**Comment by gsegria** [comment]
I use Ubuntu(Linux) to develop python script.
So , i want to write/read USB vendor command via pyusb.
When uses USB vendor command access device , needs to use SCSI Command Descriptor Block.

Any examples for scsi access in pyusb ?

**Comment by mcuee** [comment]
You should be able to translate the xusb.c example into pyusb. I will close this issue for now.

**Comment by mcuee** [comment]
Another example: ST-Link v1 libusb example.
https://github.com/stlink-org/stlink/blob/develop/src/stlink-lib/sg.c
