### ISSUE TITLE
Device._ctx.handle is None unless Device object is printed

### ISSUE THREAD

**Issue by alfiecg24** [pyusb/pyusb#441]
Hi,

I am having a weird bug, where I have a Device object that is the USB device connected.`Device._ctx` is always the correct type, but `Device._ctx.handle` is None ONLY if I don't print the value of the Device object beforehand...

![Screenshot 2022-08-03 at 23 03 59](https://user-images.githubusercontent.com/63724031/182720570-08851134-b7b7-4a09-972e-73993bf16dac.png)

This returns `Device._ctx.handle` as type `<usb.backend.libusb1._DeviceHandle object at 0x1046ef940>`. Whereas the following returns the error `AttributeError: 'NoneType' object has no attribute 'handle'`.

![Screenshot 2022-08-03 at 23 03 46](https://user-images.githubusercontent.com/63724031/182720611-75d825ac-0772-448b-9fb4-a625360bff47.png)

I have tried assigning the value of `device` to a dummy variable but it still won't work. Any ideas, or is this a pyusb bug? Thanks for any help.

**Comment by jonasmalacofilho** [comment]
That's not a bug, PyUSB automatically manages things like getting a device handle and claiming an interface, and that's done lazily.  It's the chief purpose of the `self._ctx: _ResourceManager` context.

---

On an unrelated note, can I ask why you need to into PyUSB internals just to manually do a control transfer, instead of calling the public `device.ctrl_transfer(...)` method?

**Comment by jonasmalacofilho** [comment]
> PyUSB automatically manages things like getting a device handle and claiming an interface, and that's done lazily.

For completeness, callers are not restricted to this automatic and lazy mechanism when it comes to claiming and releasing interfaces (`usb.util.claim_interface`, `usb.util.release_interface`).

**Comment by alfiecg24** [comment]
> On an unrelated note, can I ask why you need to delve into PyUSB internals just to manually do a control transfer, instead of calling the public `device.ctrl_transfer(...)` method?

This isn’t my code, it’s a fork of another project and I’ve just left it how it came 😄

**Comment by jonasmalacofilho** [comment]
Ah, I see.  It makes more sense now, it's trying to exploit a race in the USB DFU implementation in some devices...

By the way, you should have linked to the code in the first place, after all it's public.[^1]  Otherwise I'm left without useful information  for no reason... and it's not like many programmers (or even people in general) have an issue with iOS/iPadOS jailbreaking.[^2]

Anyway, the reason why the lazy behavior I described above doesn't affect checkm8 is that `DFUDevice.acquire_device` calls `usb.util.claim_interface`, which triggers the lazy mechanism in PyUSB to get the libusb1 handle.

Also I'm closing this issue since there's no bug and you probably now understand how it works.  But feel free to ask more questions.

[^1]: While I now know this code is from **checkm8,** I'm not sure which specific version/fork you're looking at, so I'm not going to link a random one here and possibly create more noise.
[^2]: And if I did have an issue with it, trying to get me to unknowingly help with it anyway wouldn't be a good solution.
