### ISSUE TITLE
Confusing documentation 

### ISSUE THREAD

**Issue by pluto-dev** [pyusb/pyusb#465]
I find the the documentation on how to install libusb on windows very confusing.

[faq](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#how-do-i-install-libusb-on-windows)

From the text I can't figure out if I should install libusb myself or if the library is enough to get going.

> On Windows, [`pyocd/libusb-package`_](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id5) is a convenient [[1]](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id3) [[2]](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id4) way to provide the necessary libusb 1.0 DLL

The [`pyocd/libusb-package`_](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id5) is just referencing the faq itself

[[1]](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id3) [[2]](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id4)  is linking to the following in the faq

> Linux and BSD are typically set up in a way in which root permissions are needed for low level/generic access to USB devices.

This is confusing, when the documentation speaks about a Windows issue but linking to an unrelevante Linux problem

**Comment by jonasmalacofilho** [comment]
> The [`pyocd/libusb-package`_](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id5) is just referencing the faq itself

That link is indeed broken. I'll fix it ASAP.

> [[1]](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id3) [[2]](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#id4) is linking to the following in the faq [...]

That's not accurate, they both point to the corresponding footnotes.

**Comment by jonasmalacofilho** [comment]
Fixed the link, but it seems that GitHub rendering of reStructuredText is broken right now: clicking the correct link results in an error, instead of opening the libusb-package project page (which exists).

![Screenshot from 2022-11-10 00-57-43](https://user-images.githubusercontent.com/1832496/200997423-e9920f1d-4285-4a69-956c-cde5e042ef8c.png)

Hopefully this will get sorted out by itself, soon. Else, I'll try to remember to report it to GitHub (but feel free to do it before me, if you can).
