### ISSUE TITLE
Incorrect usage of intf variable in pyusb tutorial for finding OUT endpoint

### ISSUE THREAD

**Issue by dtorresg** [pyusb/pyusb#477]
The [tutorial ](https://github.com/pyusb/pyusb/blob/master/docs/tutorial.rst)for pyusb on the official Github repository contains an error in the code snippet provided for finding the first OUT endpoint. The code snippet is as follows:

`ep = usb.util.find_descriptor(
    intf,
    # match the first OUT endpoint
    custom_match = \
    lambda e: \
        usb.util.endpoint_direction(e.bEndpointAddress) == \
        usb.util.ENDPOINT_OUT)`

The issue with this code is that it uses `e` as `intf`, but `intf` does not have the `bEndpointAddress` variable. Instead, `intf.endpoints()` has a list of endpoints with the bEndpointAddress variable.

This issue can be fixed by modifying the code to iterate through the list of endpoints in intf.endpoints() to find the first OUT endpoint.

I suggest the following modification to the code:

`ep = usb.util.find_descriptor(
    intf.endpoints(),
    # match the first OUT endpoint
    custom_match = \
    lambda e: \
        usb.util.endpoint_direction(e.bEndpointAddress) == \
        usb.util.ENDPOINT_OUT)`

I kindly request the maintainers to update the tutorial with this corrected code or to provide an explanation of the correct usage the library.

Thank you.

**Comment by jonasmalacofilho** [comment]
The snippet in the tutorial works perfectly fine as is. And the reason is the same as why your modification also _currently_ works: _internally,_ `find_descriptor` iterates on its `desc` parameter to find the suitable(s) inner descriptor(s). Iterating over an Interface yields its Endpoints; and `Interface.endpoints()` is just a wrapper over that.

However, `find_descriptor` expects a descriptor, not an iterator. The current implementation does just use `desc.__iter__`, but that could change in the future. So the snippet is the tutorial is correct and also the recommended usage.

(Even if `Iterface.endpoints()` might be more explicit and, thus, desirable _in other contexts)_.
